// src/app/components/hero/hero.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HeroComponent {

}

<header>
  <div class="container text-center">
    <h1 class="text-[1.75rem] leading-[2.5rem] sm:text-4xl sm:leading-[3rem]">
      Crafting Digital Dreams
    </h1>
    to make your life a little better.
  </div>
  <div class="container text-center">
    <a class="cta gradient-border" href="#">
      <div class="bg-gray-100">Check out our Solutions</div>
    </a>
  </div>
</header>

// src/components/hero/hero.tsx
import { component$, useStylesScoped$ } from "@builder.io/qwik";
import styles from "./hero.scss?inline";

export default component$(() => {
  useStylesScoped$(styles);

  return (
    <header>
      <div class="container text-center">
        <h1 class="text-[1.75rem] leading-[2.5rem] sm:text-4xl sm:leading-[3rem]">
          Crafting Digital Dreams
        </h1>
        to make your life a little better.
      </div>
      <div class="container text-center">
        <a class="cta gradient-border" href="#">
          <div class="bg-gray-100">Check out our Solutions</div>
        </a>
      </div>
    </header>
  );
});
