// src/app/components/modal/modal.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewChild,
  signal,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './modal.component.html',
  styleUrl: './modal.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ModalComponent {
  @ViewChild('modal') modal!: ElementRef;

  isModalOpen = signal(false);

  dismiss(event: any): void {
    if (!this.modal.nativeElement.contains(event.target)) {
      this.close();
    }
  }

  close(): void {
    this.isModalOpen.set(false);
  }

  open(): void {
    this.isModalOpen.set(true);
  }
}

@if (isModalOpen()) {
<div
  class="modal"
  aria-labelledby="modal-title"
  role="dialog"
  aria-modal="true"
  (click)="dismiss($event)"
>
  <div class="backdrop"></div>
  <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
    <div class="flex min-h-full items-start justify-center p-4 text-center">
      <div
        #modal
        class="relative w-full transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:max-w-lg"
      >
        <div class="body">
          <div class="sm:flex sm:items-start">
            <button (click)="close()" type="button" class="cancel">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
              >
                <path
                  fill="currentColor"
                  d="M19 6.41L17.59 5L12 10.59L6.41 5L5 6.41L10.59 12L5 17.59L6.41 19L12 13.41L17.59 19L19 17.59L13.41 12z"
                />
              </svg>
            </button>
            <div class="flex w-full flex-col gap-4 text-left">
              <h3>
                <ng-content select="modal-title"></ng-content>
              </h3>
              <div class="content">
                <ng-content></ng-content>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
}

// src/components/modal/modal.tsx
import {
  $,
  Slot,
  component$,
  useResource$,
  useSignal,
  useStylesScoped$,
} from "@builder.io/qwik";
import type { Signal } from "@builder.io/qwik";
import styles from "./modal.scss?inline";
import { IcBaselineClose } from "~/media/icons/close";

export interface ModalProps {
  isOpen: Signal<boolean>;
  class?: string;
}

export default component$((props: ModalProps) => {
  useStylesScoped$(styles);

  const modalRef = useSignal<Element>();

  useResource$(({ track }) => {
    track(() => props.isOpen.value);

    if (props.isOpen.value) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "auto";
    }
  });

  const dismiss = $((event: any) => {
    if (!modalRef.value?.contains(event.target)) {
      props.isOpen.value = false;
    }
  });

  return (
    <div
      class={`modal ${props.class} ${props.isOpen.value ? "block" : "hidden"}`}
      aria-labelledby="modal-title"
      role="dialog"
      aria-modal="true"
      onClick$={dismiss}
    >
      <div class="backdrop"></div>
      <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
        <div class="flex min-h-full items-start justify-center p-4 text-center">
          <div class="relative w-full transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:max-w-lg">
            <div class="body" ref={modalRef}>
              <div class="sm:flex sm:items-start">
                <button
                  onClick$={() => {
                    props.isOpen.value = false;
                  }}
                  type="button"
                  class="cancel"
                >
                  <IcBaselineClose class="h-7 w-7" />
                </button>
                <div class="flex w-full flex-col gap-4 text-left">
                  <h3>
                    <Slot name="title" />
                  </h3>
                  <div class="content">
                    <Slot />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
});
