// src/app/components/navbar/navbar.component.ts
import { ChangeDetectionStrategy, Component, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModalComponent } from '../modal/modal.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, ModalComponent],
})
export class NavbarComponent {
  @ViewChild('mobileNavigation') mobileNavigation!: ModalComponent;

  openMobileNavigation(): void {
    this.mobileNavigation.open();
  }
}

<nav class="z-10">
  <div class="container flex items-center justify-between">
    <div id="Navbar_Brand_Logo" class="flex items-stretch gap-1">
      <a class="text-primary" href="/">
        <svg
          width="28"
          height="28"
          viewBox="0 0 33.866666 33.866666"
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:svg="http://www.w3.org/2000/svg"
          aria-label="bytebury logo"
        >
          <g>
            <path
              style="
                fill: currentColor;
                fill-opacity: 1;
                stroke: none;
                stroke-width: 2.5967;
              "
              d="M 33.336587,20.235903 C 32.140595,25.510324 21.06655,33.832349 15.792132,32.636357 10.517712,31.440366 7.2114919,26.195061 8.4074841,20.920641 9.6034749,15.646222 14.725143,13.868993 20.123201,13.535996 28.260016,13.03405 34.532579,14.961484 33.336587,20.235903 Z M 17.871099,1.1143112 c -2.236776,0.00505 -4.883059,0.4682983 -7.694941,1.2908678 -5.1907746,1.5184752 -9.79273491,4.384418 -9.79273491,9.792735 0,4.320048 2.79781361,7.986693 6.68000021,9.287403 0.017903,-0.627102 0.09612,-1.261236 0.2400993,-1.896196 1.1959907,-5.274419 6.3176104,-7.051793 11.7156674,-7.384791 1.131189,-0.06978 2.224274,-0.09076 3.268345,-0.06417 1.375683,-2.224734 2.256612,-4.4272692 2.256612,-6.1227982 0,-3.4647028 -2.685752,-4.9120556 -6.673048,-4.9030506 z"
            />
          </g>
        </svg>
      </a>
      <a
        href="/"
        class="flex items-center rounded px-2 text-xl font-extrabold transition-colors duration-300 ease-linear hover:bg-gray-200 hover:text-gray-900"
      >
        bytebury
      </a>
    </div>

    <div id="Navbar_Links" class="hidden gap-2 md:flex">
      <ul>
        <li>
          <a class="flex items-center gap-1" href="https://github.com/bytebury">
            Open Source
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
            >
              <path
                fill="currentColor"
                d="M6 6v2h8.59L5 17.59L6.41 19L16 9.41V18h2V6z"
              />
            </svg>
          </a>
        </li>
        <li>
          <a href="/">Services</a>
        </li>
        <li>
          <a href="/">Portfolio</a>
        </li>
        <li>
          <a href="mailto:hey@bytebury.com" class="contact"> Get in Touch </a>
        </li>
      </ul>
    </div>
    <div id="Navbar_hamburger" class="flex md:hidden">
      <button
        class="hamburger"
        aria-label="Navigation Menu"
        (click)="openMobileNavigation()"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
        >
          <path
            fill="currentColor"
            d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"
          />
        </svg>
      </button>
    </div>
  </div>
</nav>
<app-modal #mobileNavigation>
  <div ngProjectAs="modal-title">Navigation</div>
  <div>
    <div class="flex flex-col gap-3">
      <ul class="modal-nav">
        <li>
          <a class="block py-2.5" href="https://github.com/bytebury">
            Open Source ✨
          </a>
        </li>
        <li>
          <a class="block py-2.5" href="/"> Services </a>
        </li>
        <li>
          <a class="block py-2.5" href="/"> Portfolio </a>
        </li>
      </ul>
      <a href="mailto:hey@bytebury.com" class="contact text-center font-bold">
        Get in Touch
      </a>
    </div>
  </div>
</app-modal>

// src/components/navbar/navbar.tsx
import { component$, useSignal, useStylesScoped$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import { APP_NAME } from "~/constants/app-constants";
import ImgLogoColored from "~/media/images/logo-colored.svg?jsx";
import styles from "./navbar.scss?inline";
import { IcOutlineMenu } from "~/media/icons/outline-menu";
import Modal from "../modal/modal";

export default component$(() => {
  useStylesScoped$(styles);

  const isMobileNavOpen = useSignal(false);

  return (
    <nav class="z-10">
      <div class="container flex items-center justify-between">
        {/* Left side navigation */}
        <div id="Navbar_Brand_Logo" class="flex items-stretch gap-1">
          <Link href="/">
            <ImgLogoColored
              style={{ width: "28px", height: "28px" }}
              aria-label={`${APP_NAME} logo`}
            />
          </Link>
          <Link
            href="/"
            class="flex items-center rounded px-2 text-xl font-extrabold transition-colors duration-300 ease-linear hover:bg-gray-200 hover:text-gray-900"
          >
            {APP_NAME}
          </Link>
        </div>
        {/* Right side navigation */}
        <div id="Navbar_Links" class="hidden gap-2 md:flex">
          <ul>
            <li>
              <a href="https://github.com/bytebury">Open Source</a>
            </li>
            <li>
              <Link href="/">Services</Link>
            </li>
            <li>
              <Link href="/">Portfolio</Link>
            </li>
            <li>
              <a href="mailto:hey@bytebury.com" class="contact">
                Get in Touch
              </a>
            </li>
          </ul>
        </div>
        {/* Hamburger menu on mobile */}
        <div id="Navbar_hamburger" class="flex md:hidden">
          <button
            class="hamburger"
            onClick$={() => (isMobileNavOpen.value = true)}
          >
            <IcOutlineMenu style={{ width: "24px", height: "24px" }} />
          </button>
        </div>
      </div>
      <Modal class="md:hidden" isOpen={isMobileNavOpen}>
        <div q:slot="title">Navigation</div>
        <div class="flex flex-col gap-3">
          <ul class="modal-nav">
            <li>
              <a class="block py-2.5" href="https://github.com/bytebury">
                Open Source ✨
              </a>
            </li>
            <li>
              <Link class="block py-2.5" href="/">
                Services
              </Link>
            </li>
            <li>
              <Link class="block py-2.5" href="/">
                Portfolio
              </Link>
            </li>
          </ul>
          <a
            href="mailto:hey@bytebury.com"
            class="contact text-center font-bold"
          >
            Get in Touch
          </a>
        </div>
      </Modal>
    </nav>
  );
});
